!template
  path: "templates/base.yaml"
  overrides:
    - !include "templates/varname_decomp.yaml"
    - model:
        decoder: "lstm"
        num_decoder_layers: 2
    - lr_scheduler:
        schedule: static
        lr: 1.0e-3
        lr_decay: 0.5
        warmup_steps: 0
    - training:
        max_batch_tokens: 3072
        grad_clip: 5.0
