!template
  path: "templates/base.yaml"
  overrides:
    - !include "templates/varname_decomp.yaml"
    - model:
        decoder: "lstm"
    - lr_scheduler:
        schedule: exponential
        lr: 5.0e-4
        scale: 0.99
        per_steps: 2000
        warmup_steps: 16000
    - training:
        max_batch_tokens: 3072
        grad_clip: 5.0
